# Generated by Django 4.0 on 2021-12-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0003_alter_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
