# Generated by Django 4.0 on 2022-01-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0004_posts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to="{%static'imgs'%}"),
        ),
    ]
