# Generated by Django 4.0 on 2022-01-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0007_category_alter_posts_image_posts_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
