# Generated by Django 4.0 on 2022-01-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0008_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
