# Generated by Django 4.0 on 2022-01-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0010_alter_category_cat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commname', models.CharField(max_length=10)),
                ('commsec', models.CharField(max_length=50)),
                ('comdate', models.DateTimeField(auto_now_add=True)),
                ('comid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodblog.posts')),
            ],
        ),
    ]
