# Generated by Django 4.0 on 2022-01-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0011_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
