# Generated by Django 4.0 on 2022-01-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0012_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dishname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commen', to='foodblog.posts'),
        ),
    ]
