# Generated by Django 4.0 on 2022-01-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0013_posts_dishname_alter_comment_comid'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='averageprice',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
