# Generated by Django 4.0 on 2022-01-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0014_posts_averageprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='averageprice',
            field=models.IntegerField(null=True),
        ),
    ]
